[package]
name = 'rjsonschema'
publish = false
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'rjsonschema'

[dependencies]
extendr-api = '*'
jsonschema = "0.26.1"
serde_json = "1.0.133"
